export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const REGISTER_USER_DEFAULT = "REGISTER_USER_DEFAULT";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_SET_DEFAULT = "LOGIN_SET_DEFAULT";
export const LOGIN_USER_GOOGLE = "LOGIN_USER_GOOGLE";

export const LOGOUT_USER = "LOGOUT_USER";

export const SET_CART = "SET_CART";
export const SET_CART_SUCCESS = "SET_CART_SUCCESS";
export const GET_CART = "GET_CART";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";
export const CLEAR_CART_ORDER = "CLEAR_CART_ORDER";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_ERROR = "ADD_TO_ERROR";
export const CHANGE_TO_CART = "CHANGE_TO_CART";
export const CHANGE_TO_CART_SUCCESS = "CHANGE_TO_CART_SUCCESS";
export const CHANGE_TO_ERROR = "CHANGE_TO_ERROR";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const REMOVE_TO_CART_SUCCESS = "REMOVE_TO_CART_SUCCESS";
export const REMOVE_TO_ERROR = "REMOVE_TO_ERROR";
export const DELETE_ALL_TO_CART = "DELETE_ALL_TO_CART";
export const DELETE_ALL_TO_CART_SUCCESS = "DELETE_ALL_TO_CART_SUCCESS";
export const DELETE_ALL_TO_ERROR = "DELETE_ALL_TO_ERROR";
export const ORDER_CART = "ORDER_CART";
export const ORDER_CART_SUCCESS = "ORDER_CART_SUCCESS";
export const ORDER_CART_ERROR = "ORDER_CART_ERROR";
export const ORDER_CART_CLEAR = "ORDER_CART_CLEAR";

export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_ERROR = "PAYMENT_ERROR";
export const PAYMENT_CLEAR = "PAYMENT_CLEAR";

export const SHOW_HIDE_MODAL = "SHOW_HIDE_MODAL";
